// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcbdsmtxzyyeitjagmjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jYmRzbXR4enl5ZWl0amFnbWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDAxNDEsImV4cCI6MjA3MjU3NjE0MX0.Hjf4v4BTiCPA9fKlhfzlz-kMXMJwMFKWoRnQO8wzD_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});